import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Godot's web export (scripts/build-godot-runner.sh), not our source.
    "public/playground/godot/**",
    // Copied from the browser-basedpyright package (scripts/copy-pyright.ts).
    "public/playground/pyright/**",
  ]),
]);

export default eslintConfig;
