/**
 * @file Build `lib/earth-map.ts`: where the land is, one bit per 2° of latitude and
 * longitude, for the home page's dithered Earth (see `lib/earth-moon.ts`).
 *
 * Usage: `bun scripts/build-earth-map.ts`. Downloads Natural Earth's 1:110m land
 * (public domain) as TopoJSON from the `world-atlas` package on jsDelivr, decodes its
 * arcs, and tests the center of each cell against the land polygons (even–odd, so
 * lakes cut out of a continent stay water).
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

const SOURCE = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json";
const OUT = path.join(import.meta.dir, "..", "lib", "earth-map.ts");
/** Cells round the equator and from pole to pole. */
const COLUMNS = 180;
const ROWS = 90;

/** The parts of a TopoJSON topology this reads. */
interface Topology {
  transform: { scale: [number, number]; translate: [number, number] };
  arcs: [number, number][][];
  objects: {
    land: { geometries: { type: string; arcs: number[][] | number[][][] }[] };
  };
}

const topology = (await (await fetch(SOURCE)).json()) as Topology;
const { scale, translate } = topology.transform;

/** Each arc as absolute [longitude, latitude] points (arcs are quantized and delta-coded). */
const arcs = topology.arcs.map((arc) => {
  let [x, y] = [0, 0];
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]] as const;
  });
});

/** A ring from its arc indices: a negative index `~i` is arc `i` reversed. */
function ring(indices: number[]): (readonly [number, number])[] {
  return indices.flatMap((index, i) => {
    const points = index < 0 ? [...arcs[~index]!].reverse() : arcs[index]!;
    return i === 0 ? points : points.slice(1);
  });
}

/**
 * A ring closed for a flat test. Antarctica's ring runs all the way round the South Pole
 * rather than enclosing it, so, read flat, it would leave the pole as sea: a ring whose
 * longitude winds a full turn is closed through the pole it goes round.
 */
function flat(points: (readonly [number, number])[]): (readonly [number, number])[] {
  let winding = 0;
  let crossing = -1;
  for (let i = 1; i < points.length; i++) {
    const step = points[i]![0] - points[i - 1]![0];
    if (Math.abs(step) > 180) crossing = i;
    winding += step > 180 ? step - 360 : step < -180 ? step + 360 : step;
  }
  if (Math.abs(winding) < 180 || crossing < 0) return points;
  // Open the ring where it crosses the date line, so it runs from one side of the map to
  // the other, then close it along the pole's edge of the map.
  const open = [...points.slice(crossing), ...points.slice(1, crossing)];
  const pole = points.reduce((sum, [, latitude]) => sum + latitude, 0) < 0 ? -90 : 90;
  return [...open, [open.at(-1)![0], pole], [open[0]![0], pole]];
}

const rings = topology.objects.land.geometries.flatMap((geometry) => {
  const polygons = (geometry.type === "Polygon" ? [geometry.arcs] : geometry.arcs) as number[][][];
  return polygons.flatMap((polygon) => polygon.map((indices) => flat(ring(indices))));
});

/** Whether a point is inside an odd number of rings. */
function isLand(longitude: number, latitude: number): boolean {
  let inside = false;
  for (const points of rings) {
    for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
      const [xi, yi] = points[i]!;
      const [xj, yj] = points[j]!;
      if (
        yi > latitude !== yj > latitude &&
        longitude < ((xj - xi) * (latitude - yi)) / (yj - yi) + xi
      ) {
        inside = !inside;
      }
    }
  }
  return inside;
}

// Row 0 is the northernmost band and column 0 starts at 180° W; bits run row by row,
// most significant bit first.
const bytes = new Uint8Array((COLUMNS * ROWS) / 8);
for (let row = 0; row < ROWS; row++) {
  for (let column = 0; column < COLUMNS; column++) {
    const latitude = 90 - ((row + 0.5) * 180) / ROWS;
    const longitude = -180 + ((column + 0.5) * 360) / COLUMNS;
    if (isLand(longitude, latitude)) {
      const i = row * COLUMNS + column;
      bytes[i >> 3]! |= 0x80 >> (i & 7);
    }
  }
}

const encoded = Buffer.from(bytes).toString("base64");
const lines = encoded.match(/.{1,88}/g)!.map((line) => `  "${line}",`);
writeFileSync(
  OUT,
  `/**
 * @file Where the land is on Earth, ${COLUMNS} × ${ROWS} cells of ${360 / COLUMNS}°: generated by
 * \`scripts/build-earth-map.ts\` from Natural Earth's 1:110m land (public domain). Do not edit.
 *
 * Base64 of one bit per cell, 1 for land, row by row from the north pole and from 180° W,
 * most significant bit first.
 */

/** Cells round the equator. */
export const EARTH_MAP_COLUMNS = ${COLUMNS};
/** Cells from pole to pole. */
export const EARTH_MAP_ROWS = ${ROWS};
/** The land bits, base64. */
export const EARTH_MAP = [
${lines.join("\n")}
].join("");
`,
);
const land = [...bytes].reduce((sum, byte) => sum + byte.toString(2).replaceAll("0", "").length, 0);
console.log(
  `${OUT}: ${land} of ${COLUMNS * ROWS} cells land (${((100 * land) / (COLUMNS * ROWS)).toFixed(1)}%)`,
);
